name: "Generate PostgreSQL ER Diagram (Mermaid)"
description: "Generate ER diagram in Mermaid from PostgreSQL database and update README"
author: "ViniciusDev26"
branding:
  icon: "database"
  color: "blue"

inputs:
  db-host:
    description: "Host of PostgreSQL"
    required: false
    default: "localhost"
  db-port:
    description: "Port of PostgreSQL"
    required: false
    default: "5432"
  db-name:
    description: "Name of the database"
    required: true
  db-user:
    description: "User of the database"
    required: true
  db-pass:
    description: "Password of the database"
    required: true
  output-dir:
    description: "Directory where the diagram will be saved"
    required: false
    default: "docs"
  write-to-readme:
    description: "Whether to write the diagram to the README file"
    required: false
    default: "false"
  readme-path:
    description: "Path to the README file"
    required: false
    default: "README.md"
  excluded-tables:
    description: "Comma-separated list of table names to exclude from the diagram"
    required: false
    default: "flyway_schema_history"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Generate ER diagram
      env:
        DB_HOST: ${{ inputs.db-host }}
        DB_PORT: ${{ inputs.db-port }}
        DB_NAME: ${{ inputs.db-name }}
        DB_USER: ${{ inputs.db-user }}
        DB_PASS: ${{ inputs.db-pass }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        WRITE_TO_README: ${{ inputs.write-to-readme }}
        README_PATH: ${{ inputs.readme-path }}
        EXCLUDED_TABLES: ${{ inputs.excluded-tables }}
      run: bun run $GITHUB_ACTION_PATH/src/generate-pg-diagram.ts
      shell: bash
