name: "Generate PostgreSQL ER Diagram (Mermaid)"
description: "Generate ER diagram in Mermaid from PostgreSQL database and update README"
author: "ViniciusDev26"
branding:
  icon: "database"
  color: "blue"

inputs:
  pg-host:
    description: "Host of PostgreSQL"
    required: false
    default: "localhost"
  pg-port:
    description: "Port of PostgreSQL"
    required: false
    default: "5432"
  pg-database:
    description: "Name of the database"
    required: true
  pg-user:
    description: "User of the database"
    required: true
  pg-password:
    description: "Password of the database"
    required: true
  output-dir:
    description: "Directory where the diagram will be saved"
    required: false
    default: "docs"
  write-to-readme:
    description: "Whether to write the diagram to the README file"
    required: false
    default: "false"
  readme-path:
    description: "Path to the README file"
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Generate ER diagram
      env:
        PGHOST: ${{ inputs.pg-host }}
        PGPORT: ${{ inputs.pg-port }}
        PGDATABASE: ${{ inputs.pg-database }}
        PGUSER: ${{ inputs.pg-user }}
        PGPASSWORD: ${{ inputs.pg-password }}
        WRITE_TO_README: ${{ inputs.write-to-readme }}
        README_PATH: ${{ inputs.readme-path }}
      run: bun run $GITHUB_ACTION_PATH/src/generate-pg-diagram.ts
      shell: bash
