name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-postgresql:
    name: PostgreSQL Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.9-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: er-diagram
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Wait for PostgreSQL
        run: |
          echo "⏳ Waiting for PostgreSQL..."
          timeout 60 bash -c 'until pg_isready -h localhost -p 5432 -U postgres; do sleep 2; done'
          echo "✅ PostgreSQL is ready"

      - name: Load PostgreSQL schema
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d er-diagram -f migrations/postgres/001_init.sql

      - name: Run PostgreSQL integration tests
        run: bun run test:postgresql

  test-mysql:
    name: MySQL Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.1.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: er-diagram
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Wait for MySQL
        run: |
          echo "⏳ Waiting for MySQL..."
          timeout 60 bash -c 'until mysqladmin ping -h 127.0.0.1 -P 3306 --silent 2>/dev/null; do sleep 2; done'
          echo "✅ MySQL is ready"

      - name: Load MySQL schema
        run: |
          MYSQL_PWD=root mysql -h 127.0.0.1 -P 3306 -u root er-diagram < migrations/mysql/001_init.sql

      - name: Run MySQL integration tests
        run: bun run test:mysql

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test-postgresql, test-mysql]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx semantic-release
