name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.9-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: er-diagram
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mysql:9.1.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: er-diagram
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Wait for databases to be ready
        run: |
          echo "⏳ Waiting for PostgreSQL..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 2
          done
          echo "✅ PostgreSQL is ready"

          echo "⏳ Waiting for MySQL..."
          until mysqladmin ping -h localhost -P 3306 -u root -proot --silent; do
            sleep 2
          done
          echo "✅ MySQL is ready"

      - name: Load PostgreSQL schema
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d er-diagram -f migrations/postgres/001_init.sql

      - name: Load MySQL schema
        run: |
          mysql -h localhost -P 3306 -u root -proot er-diagram < migrations/mysql/001_init.sql

      - name: Run integration tests
        run: bun test

      - name: Run PostgreSQL integration tests
        run: bun run test:postgresql

      - name: Run MySQL integration tests
        run: bun run test:mysql
